AppBlog/urls.py
from django.urls import path
from AppBlog import views
app_name = 'AppBlog'
urlpatterns = [
    path('create/', views.createArticle, name="createblog"),
    path('', views.ArticleList.as_view(), name='articles'),
    path('<slug>/', views.ArticleDetail.as_view(), name='articledetails')
]

EduSite/urls.py
from django.contrib import admin
from django.urls import path, include
from EduSite import views
urlpatterns = [
    path('', views.index, name="homepage"),
    path('admin/', admin.site.urls),
    path('articles/', include('AppBlog.urls')),
    path('forum/', include('AppForum.urls')),
    path('accounts/', include('AppLogin.urls')),
    path('quizes/', include('AppQuiz.urls')),
]

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppBlog/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'Categories'
    
class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blogauthor')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='blogcategory')
    title = models.CharField(max_length=300)
    content = models.TextField()
    slug = models.SlugField(max_length=600, unique=True)
    poster = models.ImageField(upload_to='Blog_Posters/')

    publish = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-publish']
    def __str__(self):
        return f"{self.title} by {self.author}"

AppBlog/forms.py
from django import forms
from .models import Article, Category
class AddCategory(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'category', 'content', 'poster')
        labels = {
            'title': 'Article Title',
            'content': 'Article',
            'poster': 'Article Poster',
        }

AppBlog/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import ArticleForm, AddCategory
from .models import Article
from AppLogin.decorators import student_required, teacher_required
from uuid import uuid4
from django.urls import reverse
from django.views.generic import ListView, DetailView
# Create your views here.
@teacher_required()
def createArticle(req):
    form = AddCategory()
    if req.method == 'POST':
        form = AddCategory(req.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('AppBlog:createblog'))
    form2 = ArticleForm()
    if req.method == 'POST':
        form2 = ArticleForm(req.POST, req.FILES)
        if form2.is_valid():
            obj = form2.save(commit=False)
            obj.author = req.user
            title = obj.title
            obj.slug = title.replace(' ', '-') + "-" + str(uuid4())
            obj.save()
            return HttpResponseRedirect(reverse('homepage'))
    return render(req, 'AppBlog/createArticle.html', context={'category':form,'form':form2})

class ArticleList(ListView):
    model = Article
    template_name = "AppBlog/articlelist.html"
    context_object_name = 'articles'

class ArticleDetail(DetailView):
    model = Article
    template_name = "AppBlog/articledetail.html"
    context_object_name = 'article'

templates/AppBlog/articledetail.html
{% extends "base.html" %}
{% block title %}
  {{article.title}}
{% endblock title %}
{% block body %}
  <small class="mb-3">{{article.category}}</small>
  <h3 class="mb-4">{{article.title}}</h3>
  <div class="d-flex gap-3 mb-4">
    <img src="/media/{{article.author.teacherprofile.profilepic}}" width="50px" height="50px" alt="" srcset="">
    <div class="">
        <h5 class="mb-1">{{article.author}}</h5>
        <small>{{article.publish|date:"M d, Y"}}</small>
    </div>
  </div>
  <img class="w-75 mb-3" src="/media/{{article.poster}}" alt="" srcset="">
  <p>{{article.content|linebreaks}}</p>

  {% endblock body %}

templates/AppBlog/articlelist.html
{% extends "base.html" %}
{% load custom_filters %}
{% load static %}
{% block title %}
  Articles by our Teachers
{% endblock title %}
{% block body %}
  {% for article in articles %}
    <div class="card mb-4">
      <div class="row">
        <div class="col-sm-8">
          <img class="w-100 h-100 rounded-start-3" src="/media/{{article.poster}}" alt="{{article.title}}" srcset="">
        </div>
        <div class="col-sm-4 pt-4">
          <small class="w-100 text-danger fw-bold mb-2">{{article.category}}</small>
          <div class="card-header w-100 bg-transparent border-0 fs-4 mb-2 fw-bold">{{article.title}}</div>
          <div class="card-body w-100">
            <p>{{article.content|ellipsis}} <a href="{% url 'AppBlog:articledetails' slug=article.slug %}" class="link-danger">Read More >></a></p>
            <p><a href="" class="text-danger text-decoration-none">{{article.author}} ⸱ </a>{{article.publish|date:"M d, Y"}}</p>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock body %}

templates/AppBlog/createArticle.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  Create Blog
{% endblock title %}
{% block body %}
  <h3 class="mb-3">Add Category</h3>
  <div class="w-100">
    <form action="" method="POST" class="mb-4">
      {{ category|crispy }}
      {% csrf_token %}
      <input type='submit' value='Add+' class="btn btn-success">
    </form>
  </div>
  <h3 class="mb-3">Create an Article</h3>
  <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" name='create' value=True  class="btn btn-primary mt-2 mb-4 ">Publish!</button>
  </form>
{% endblock body %}