AppBlog/urls.py
from django.urls import path
from AppBlog import views
app_name = 'AppBlog'
urlpatterns = [
    path('create/', views.createArticle, name="createblog"),
    path('', views.ArticleList.as_view(), name='articles'),
    path('<slug>/', views.ArticleDetail.as_view(), name='articledetails')
]

AppQuiz/urls.py
from django.urls import path
from AppQuiz import views
app_name = 'AppQuiz'
urlpatterns = [
    path('',views.AllQuiz.as_view(), name='quizhome'),
    path('myquiz/', views.MyQuiz, name='myquizes'),
    path('createquiz/', views.create_quiz, name='createquiz'),
    path('<pk>/', views.quiz_details, name='quizdetails'),
    path('customize/<pk>/', views.customize_quiz, name='customizequiz'),
    path('exam/<pk>/', views.givequiz, name='inquiz'),
    path('result/<pk>/', views.quizresult, name='quizresult'),
]

EduSite/urls.py
from django.contrib import admin
from django.urls import path, include
from EduSite import views
urlpatterns = [
    path('', views.index, name="homepage"),
    path('admin/', admin.site.urls),
    path('articles/', include('AppBlog.urls')),
    path('forum/', include('AppForum.urls')),
    path('accounts/', include('AppLogin.urls')),
    path('quizes/', include('AppQuiz.urls')),
]

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppQuiz/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Quiz(models.Model):
    title = models.CharField(max_length=200)
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='teacherquiz')
    description = models.TextField()
    duration = models.IntegerField()
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Quiz: {self.title}"
class MCQ(models.Model):
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='teachermcq')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quizmcq')
    question = models.CharField(max_length=2000)
    option1  = models.CharField(max_length=2000)
    option2   = models.CharField(max_length=2000)
    option3 = models.CharField(max_length=2000)
    option4 = models.CharField(max_length=2000)
    correctOption = models.IntegerField()
    
    def __str__(self):
        return f"Question: {self.question}"

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quizresult')
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='studentresult')
    score = models.IntegerField()
    # time = models.IntegerField()
    def __str__(self):
        return f"{self.student}'s Score = {self.score}"
    class Meta:
        ordering = ['-score']

AppQuiz/forms.py
from .models import Quiz, MCQ, Result
from django import forms

class CreateQuiz(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['title', 'description', 'duration']
        labels = {
            'title':'Quiz Name',
            'description': 'Quiz Description',
            'duration': 'Duration (in minutes)'
        }
class CreateMCQ(forms.ModelForm):
    class Meta:
        model = MCQ
        fields = [
            'question',
            'option1',
            'option2',
            'option3',
            'option4',
            'correctOption',
        ]
        labels = {
            'question': 'Question',
            'option1': 'Option 1',
            'option2': 'Option 2',
            'option3': 'Option 3',
            'option4': 'Option 4',
            'correctOption': "Correct Answer(1-4)",
        }

class ResultForm(forms.ModelForm):
    class Meta:
        model= Result
        exclude = ['quiz', 'student', 'score']

AppQuiz/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .models import Quiz, MCQ, Result
from django.views.generic import ListView
from .forms import CreateQuiz, CreateMCQ, ResultForm
from AppLogin.decorators import teacher_required, student_required
# Create your views here.

class AllQuiz(ListView):
    model = Quiz
    template_name = 'AppQuiz/allquiz.html'
    context_object_name = 'quizes'
@teacher_required()
def MyQuiz(req):
    quizes = Quiz.objects.filter(teacher=req.user)
    return render(req, 'AppQuiz/myquiz.html', context={'quizes':quizes})

@teacher_required()
def create_quiz(req):
    form = CreateQuiz()
    if req.method == "POST":
        form = CreateQuiz(req.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.teacher = req.user
            quiz.save()
            return HttpResponseRedirect(reverse('AppQuiz:myquizes'))
    return render(req, 'AppQuiz/createquiz.html', context={'form':form})

def quiz_details(req, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(req, 'AppQuiz/quizdetails.html', context={'quiz':quiz})

@teacher_required()
def customize_quiz(req, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = MCQ.objects.filter(quiz=quiz, teacher=req.user)
    form = CreateMCQ()
    if req.method == "POST":
        form = CreateMCQ(req.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.teacher = req.user
            question.save()
            return HttpResponseRedirect(reverse('AppQuiz:customizequiz', kwargs={'pk':pk}))
    return render(req, 'AppQuiz/customizequiz.html', context={'quiz':quiz, 'questions':questions, 'form':form})
@student_required()
def givequiz(req, pk):
    quiz = Quiz.objects.get(pk=pk)
    ques = MCQ.objects.filter(quiz=quiz)
    questions = [x.question for x in ques]
    answers = [str(x.correctOption) for x in ques]
    score = 0
    form = ResultForm()
    if(req.method == 'POST'):
        form = ResultForm(req.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.quiz = quiz
            obj.student = req.user
            data = req.POST
            for i in range(len(questions)):
                if(data[questions[i]] == answers[i]):
                    score += 1
            obj.score = score
            print(obj)
            obj.save()
    return render(req, 'AppQuiz/thequiz.html', context={'ques':ques, 'quiz':quiz, 'score':score, 'form':form})
@teacher_required()
def quizresult(req, pk):
    quiz = Quiz.objects.get(pk=pk)
    results = Result.objects.filter(quiz=quiz)
    return render(req, 'AppQuiz/quizresults.html', {'results':results,'quiz':quiz})

templates/AppQuiz/allquiz.html
{% extends "base.html" %}
{% load custom_filters2 %}
{% block title %}
  Participate & Test Yourself
{% endblock title %}
{% block body %}
  {% for quiz in quizes %}
    <div class="card p-5 w-50 d-flex align-items-center">
      <div class="card-title">{{quiz.title}}</div>
      <div class="card-subtitle mb-4">By {{quiz.teacher.first_name}} {{quiz.teacher.last_name}} |
        <small class="text-muted">{{quiz.date_created|date:'M d, Y'}}</small>
      </div>
      
      <p class="mb-4">{{quiz.description|ellipsis}}</p>
      <a href="{% url 'AppQuiz:quizdetails' pk=quiz.pk %}" class="btn btn-primary w-100 text-center">Details</a>
    </div>
  {% endfor %}
{% endblock body %}

templates/AppQuiz/createquiz.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  Create Quiz
{% endblock title %}

{% block body %}
  <h3 class="mb-3">Create a quiz</h3>
  <form method='POST'>
    {% csrf_token %}
    {{ form|crispy }}
    <button type='submit' class='btn btn-primary mt-2'>Create Quiz</button>
  </form>
{% endblock body %}

templates/AppQuiz/customizequiz.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  Customize {{quiz.title}}
{% endblock title %}
{% block body %}
    <div class="form">
        <h3 class="mb-3">
            Add Question
        </h3>
        <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-success">Add +</button>
        </form>
    </div>
  <table class="table table-bordered mt-5">
    <thead>
        <th>Question no.</th>
        <th>Question</th>
        <th>Option 1</th>
        <th>Option 2</th>
        <th>Option 3</th>
        <th>Option 4</th>
        <th>Correct Answer</th>
    </thead>
    <tbody>
        {% for question in questions %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{question.question}}</td>
            <td>{{question.option1}}</td>
            <td>{{question.option2}}</td>
            <td>{{question.option3}}</td>
            <td>{{question.option4}}</td>
            <td>{{question.correctOption}}</td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock body %}

templates/AppQuiz/myquiz.html
{% extends "base.html" %}
{% load custom_filters2 %}
{% block title %}
  My Quizes
{% endblock title %}
{% block body %}
    <a href="{% url 'AppQuiz:createquiz' %}" class="btn btn-primary mb-5">Create Quiz +</a>
  {% for quiz in quizes %}
    {% if quiz.teacher == user %}
        <div class="card p-5 w-50 d-flex align-items-center">
          <div class="card-title">{{quiz.title}}</div>
          <div class="card-subtitle mb-4">By {{quiz.teacher.first_name}} {{quiz.teacher.last_name}} |
            <small class="text-muted">{{quiz.date_created|date:'M d, Y'}}</small>
          </div>
          <p class="mb-4">{{quiz.description|ellipsis}}</p>
          <a href="{% url 'AppQuiz:customizequiz' pk=quiz.pk %}" class="btn btn-danger w-100 text-center mb-4">Customize</a>
          <a href="{% url 'AppQuiz:quizresult' pk=quiz.pk %}" class="btn btn-success w-100">Result</a>
        </div>
    {% endif %}
  {% endfor %}
{% endblock body %}

templates/AppQuiz/quizdetails.html
{% extends "base.html" %}
{% block title %}
  {{quiz.title}}
{% endblock title %}
{% block body %}
<div class="card p-5 w-100 d-flex align-items-start">
    <h3 class="card-title">{{quiz.title}}</h3>
    <h6 class="card-subtitle">By {{quiz.teacher.first_name}} {{quiz.teacher.last_name}}</h6>
    <small class="text-muted mb-4">{{quiz.date_created|date:'M d, Y'}}</small>
    <p class="mb-4">{{quiz.description|linebreaks}}</p>
    <a href="{% url 'AppQuiz:inquiz' pk=quiz.pk %}" class="btn btn-primary w-100 text-center">Take Quiz</a>
  </div>
{% endblock body %}

templates/AppQuiz/quizresults.html
{% extends "base.html" %}
{% block title %}
  Result of {{quiz.title}}
{% endblock title %}
{% block body %}
  <table class="table table-bordered">
    <thead>
        <th>Student Name</th>
        <th>Score</th>
    </thead>
    <tbody>
        {% for result in results %}
          <tr>
            <td>{{result.student.first_name}} {{result.student.last_name}}</td>
            <td>{{result.score}}</td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock body %}

templates/AppQuiz/thequiz.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  Quiz
{% endblock title %}
{% block body %}
  <h2 class="w-100 text-center mb-5">{{quiz.title}}</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {% for que in ques %}
    <div class="card mb-3 px-5 py-3">
        <h6>{{forloop.counter}}. {{que.question}}</h6>
        <div class="all-groups d-flex gap-3 justify-content-start align-items-center">
            <div class="form-group">
                <input type="radio" name="{{que.question}}" id="" value="1">
                <label for="{{que.question}}">{{que.option1}}</label>
            </div>
            <div class="form-group">
                <input type="radio" name="{{que.question}}" id="" value="2">
                <label for="{{que.question}}">{{que.option2}}</label>
              </div>
              <div class="form-group">
                <input type="radio" name="{{que.question}}" id="" value="3">
                <label for="{{que.question}}">{{que.option3}}</label>
              </div>
              <div class="form-group">
                <input type="radio" name="{{que.question}}" id="" value="4">
                <label for="{{que.question}}">{{que.option4}}</label>
              </div>
        </div>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary w-100">Submit</button>
  </form>
{% endblock body %}