AppBlog/urls.py
from django.urls import path
from AppBlog import views
app_name = 'AppBlog'
urlpatterns = [
    path('create/', views.createArticle, name="createblog"),
    path('', views.ArticleList.as_view(), name='articles'),
    path('<slug>/', views.ArticleDetail.as_view(), name='articledetails')
]

AppForum/urls.py
from django.urls import path
from AppForum import views
app_name = 'AppForum'
urlpatterns = [
    path('ask/', views.ForumCreate, name='createforum'),
    path('', views.ForumList.as_view(), name='forumlist'),
    path('question/<pk>/', views.forumdetails, name="details"),
    path('myquestions/', views.myquestions, name='myquestions')
]

AppLogin/urls.py
from django.urls import path
from AppLogin import views
app_name = 'AppLogin'
urlpatterns = [
    path('signup/', views.signupUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/', views.profileUser, name='profile'),
    path('edit_profile/', views.editprofileUser, name='editprofile'),
]

AppQuiz/urls.py
from django.urls import path
from AppQuiz import views
app_name = 'AppQuiz'
urlpatterns = [
    path('',views.AllQuiz.as_view(), name='quizhome'),
    path('myquiz/', views.MyQuiz, name='myquizes'),
    path('createquiz/', views.create_quiz, name='createquiz'),
    path('<pk>/', views.quiz_details, name='quizdetails'),
    path('customize/<pk>/', views.customize_quiz, name='customizequiz'),
    path('exam/<pk>/', views.givequiz, name='inquiz'),
    path('result/<pk>/', views.quizresult, name='quizresult'),
]

EduSite/urls.py
from django.contrib import admin
from django.urls import path, include
from EduSite import views
urlpatterns = [
    path('', views.index, name="homepage"),
    path('admin/', admin.site.urls),
    path('articles/', include('AppBlog.urls')),
    path('forum/', include('AppForum.urls')),
    path('accounts/', include('AppLogin.urls')),
    path('quizes/', include('AppQuiz.urls')),
]

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js' integrity='sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL' crossorigin='anonymous'></script>
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN' crossorigin='anonymous'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css' integrity='sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==' crossorigin='anonymous' referrerpolicy='no-referrer' />
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' integrity='sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==' crossorigin='anonymous' referrerpolicy='no-referrer' />
    <title>{% block title %}
        Educational Website
    {% endblock title %} | Edusite</title>
</head>
<body style="min-height: 100vh; display: flex; flex-direction: column;">
    {% include "navbar.html" %}

    <div class="container mb-5">
        <!-- Div to show warnings, success, info messages -->
        <div class="messages container mt-2">
            {% if messages %}
              {% for message in messages %}
                <div {% if message.tags %}
                class="alert alert-{{message.tags}} alert-dismissible fade show"
                {% endif %}
                role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              {% endfor %}
            {% endif %}
        </div>
        {% block body %}
      
    {% endblock body %}
    </div>
    <footer class="mt-5 mt-auto">
        <div class="bg-secondary py-3 text-white text-center">Developed By Abdullah Sheehan!</div>
    </footer>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light px-5 py-3 mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'homepage' %}">EduSite</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav w-100 mb-2 mb-lg-0  d-flex justify-content-end align-items-center">
          <!-- Authentication -->
          {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'AppLogin:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'AppLogin:register' %}">Register</a>
          </li>
          {% endif %}
          
          {% if user.is_authenticated %}
          <!-- Dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{user.first_name}} {{user.last_name}}
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <!-- Forums -->
              <li><a class="dropdown-item" href="{% url 'AppForum:forumlist' %}">Forums</a></li>
              {% if user.is_teacher %}
              <!-- Article -->
              <li><a class="dropdown-item" href="{% url 'AppBlog:createblog' %}">Publish an Article</a></li>
              {% endif %}
              {% if user.is_student %}
              <!-- Forum -->
              <li><a class="dropdown-item" href="{% url 'AppForum:createforum' %}">Ask a Question</a></li>
              <li><a class="dropdown-item" href="{% url 'AppForum:myquestions' %}">My Questions</a></li>
              {% endif %}
              <li class="dropdown-divider"></li>
              <!-- Quiz  -->
              <li><a class="dropdown-item" href="{% url 'AppQuiz:quizhome' %}">Quizes</a></li>
              {% if user.is_teacher %}
              <li><a class="dropdown-item" href="{% url 'AppQuiz:myquizes' %}">My Quizes</a></li>
              {% endif %}
              <!-- Profile & Logout -->
              <li class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'AppLogin:profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'AppLogin:logout' %}">Logout</a></li>
            </ul>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>